docker stop bitnami-kafka_kafka_producer
docker rm bitnami-kafka_kafka_producer

docker run `
--name bitnami-kafka_kafka_producer `
-e KAFKA_ENABLE_KRAFT=yes `
-e KAFKA_CFG_PROCESS_ROLES=broker,controller `
-e KAFKA_CFG_NODE_ID=1 `
-e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093 `
-e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER `
-e KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9093 `
-e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9094 `
-e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT `
-p 9094:9094 `
-d `
bitnami/kafka